#!/bin/sh

# Terminal Colors
export PURP='\033[0;35m'
export BLU='\033[0;34m'
export YEL='\033[0;33m'
export RED='\033[0;31m'
export GRN='\033[0;92m'
export WHT='\033[0;37m'
export NC='\033[0m' # No Color

report_status() {
    local status=$1  # "error" or "success"
    local message=$2 # Message to display

    case $status in
    error)
        echo -e "${RED}🚫 Error:${WHT} $message${NC}"
        ;;
    success)
        echo -e "${GRN}$message${WHT}${NC}\n"
        ;;
    *)
        echo -e "${WHT}$message${NC}"
        ;;
    esac
}
